version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - '85:3050'
    environment:
      - DB_CONNECT=mongodb://mongo:27017/resume-system
      - PORT=3050
      - NODE_ENV=production
      - SESSION_NAME=sid
      - SESSION_SECRET=thisisagoodsecrettokeepdocker
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
  node_modules: