version: '3'
services:
  app:
    container_name: resume-system
    restart: always
    build: .
    ports:
      - '85:3035'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
